"""
Django settings for college_management_system project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent
FRONTEND_DIR = ROOT_DIR / 'frontend'

# --- Load .env File Configurations ---
env_path = ROOT_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                # Remove quotes if present
                val = val.strip().strip("'\"")
                os.environ[key.strip()] = val

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'f2zx8*lb*em*-*b+!&1lpp&$_9q9kmkar+l3x90do@s(+sr&x7')

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get('VERCEL') and 'DEBUG' not in os.environ:
    DEBUG = False
else:
    DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*,.vercel.app,.onrender.com').split(',')

# Vercel sets VERCEL_URL automatically (e.g. my-app.vercel.app)
if os.environ.get('VERCEL_URL'):
    vercel_host = os.environ['VERCEL_URL']
    if vercel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_host)

# Render sets RENDER_EXTERNAL_HOSTNAME automatically
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    render_host = os.environ['RENDER_EXTERNAL_HOSTNAME']
    if render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_host)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if os.environ.get('VERCEL_URL'):
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ['VERCEL_URL']}")
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ['RENDER_EXTERNAL_HOSTNAME']}")


def _build_supabase_direct_url():
    """Build direct Supabase Postgres URL from individual POSTGRES_* vars."""
    host = os.environ.get('POSTGRES_HOST')
    password = os.environ.get('POSTGRES_PASSWORD')
    if not host or not password:
        return None
    user = os.environ.get('POSTGRES_USER', 'postgres')
    database = os.environ.get('POSTGRES_DATABASE', 'postgres')
    return f'postgresql://{user}:{password}@{host}:5432/{database}?sslmode=require'


def _clean_postgres_url(url_str):
    """Clean invalid connection options (e.g. pgbouncer, supa) from Postgres URL."""
    if not url_str:
        return url_str
    if not (url_str.startswith('postgres://') or url_str.startswith('postgresql://')):
        return url_str
    from urllib.parse import urlparse, parse_qsl, urlencode, urlunparse
    try:
        parsed = urlparse(url_str)
        qsl = parse_qsl(parsed.query)
        allowed = {'sslmode', 'sslrootcert', 'sslcert', 'sslkey', 'connect_timeout'}
        clean_qsl = [(k, v) for k, v in qsl if k in allowed]
        new_query = urlencode(clean_qsl)
        return urlunparse((
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            parsed.params,
            new_query,
            parsed.fragment
        ))
    except Exception:
        return url_str


def get_database_url():
    """Resolve Postgres URL from Supabase/Vercel env vars, else SQLite."""
    for key in (
        'DATABASE_URL',
        'POSTGRES_PRISMA_URL',  # Supabase/Vercel pooled connection (runtime)
        'POSTGRES_URL',
    ):
        url = os.environ.get(key)
        if url:
            return _clean_postgres_url(url)
    direct = _build_supabase_direct_url()
    if direct:
        return _clean_postgres_url(direct)
    return f'sqlite:///{BASE_DIR / "db.sqlite3"}'


def get_migrations_database_url():
    """Direct connection for migrations (avoid transaction pooler)."""
    direct = _build_supabase_direct_url()
    if direct:
        return _clean_postgres_url(direct)
    for key in ('POSTGRES_URL_NON_POOLING', 'DATABASE_URL'):
        url = os.environ.get(key)
        if url:
            return _clean_postgres_url(url)
    return get_database_url()

# Application definition

SHARED_APPS = (
    'django_tenants',
    'saas_admin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_app.apps.MainAppConfig',
)

TENANT_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main_app.apps.MainAppConfig',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "saas_admin.Client"
TENANT_DOMAIN_MODEL = "saas_admin.Domain"
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Third Part Middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'college_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'college_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if 'migrate' in sys.argv and os.environ.get('POSTGRES_HOST'):
    _database_url = get_migrations_database_url()
else:
    _database_url = get_database_url()
_using_postgres = _database_url.startswith(('postgres://', 'postgresql://'))

if _using_postgres:
    try:
        import psycopg2
        parsed_db = dj_database_url.parse(_database_url)
        # Fast 3-second timeout check
        conn = psycopg2.connect(
            dbname=parsed_db.get('NAME', ''),
            user=parsed_db.get('USER', ''),
            password=parsed_db.get('PASSWORD', ''),
            host=parsed_db.get('HOST', ''),
            port=parsed_db.get('PORT', 5432),
            connect_timeout=3
        )
        conn.close()
    except Exception as e:
        print("\n" + "="*60)
        print("!!! CRITICAL DATABASE ERROR !!!")
        print("="*60)
        print(f"Could not connect to the PostgreSQL database at: {parsed_db.get('HOST', 'Unknown')}")
        print(f"Error Details: {e}")
        print("-" * 60)
        print("The College ERP uses 'django-tenants', which strictly requires PostgreSQL.")
        print("If you are using Supabase, it might be paused or unreachable.")
        print("Please check your .env file or start a local Postgres server.")
        print("="*60 + "\n")
        sys.exit(1)

DATABASES = {
    'default': dj_database_url.config(
        default=_database_url,
        conn_max_age=600 if _using_postgres else 0,
        conn_health_checks=_using_postgres,
        ssl_require=_using_postgres,
        engine='django_tenants.postgresql_backend',
    ),
    'legacy_sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
if not DEBUG:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    FRONTEND_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    FRONTEND_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
AUTH_USER_MODEL = 'main_app.CustomUser'
AUTHENTICATION_BACKENDS = [
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'main_app.EmailBackend.EmailBackend',
]
TIME_ZONE = 'Asia/Kolkata'

# Session Configuration for Remember Me functionality
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (default)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # This will be overridden by remember me
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request to extend expiry

# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_mails")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '')
EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "School Management System <admin@admin.com>"

# Redis Cache & Sessions (graceful fallback to DB sessions if Redis is unavailable)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')
try:
    import redis as _redis_client
    _r = _redis_client.from_url(REDIS_URL, socket_connect_timeout=1)
    _r.ping()  # Test connectivity
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
except Exception:
    # Redis not available — use default local memory cache and DB sessions
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# S3/MinIO Storage Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') # MinIO support
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
AWS_S3_FILE_OVERWRITE = False

if AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

WHITENOISE_MANIFEST_STRICT = False

# Supabase (optional — for future API/storage integrations)
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_ANON_KEY = os.environ.get('NEXT_PUBLIC_SUPABASE_ANON_KEY', '')
SUPABASE_SERVICE_ROLE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY', '')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# --- Security Configuration Enhancements ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# --- Celery Configuration ---
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/1')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# --- Keycloak (mozilla-django-oidc) Configuration ---
OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', 'college-erp')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET', 'secret')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT', 'http://keycloak:8080/realms/college/protocol/openid-connect/auth')
OIDC_OP_TOKEN_ENDPOINT = os.environ.get('OIDC_OP_TOKEN_ENDPOINT', 'http://keycloak:8080/realms/college/protocol/openid-connect/token')
OIDC_OP_USER_ENDPOINT = os.environ.get('OIDC_OP_USER_ENDPOINT', 'http://keycloak:8080/realms/college/protocol/openid-connect/userinfo')
OIDC_OP_JWKS_ENDPOINT = os.environ.get('OIDC_OP_JWKS_ENDPOINT', 'http://keycloak:8080/realms/college/protocol/openid-connect/certs')
OIDC_RP_SIGN_ALGO = 'RS256'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# --- Socket.IO configuration (via python-socketio) ---
# Will be mounted as an ASGI app if Daphne/Uvicorn is used, 
# for now settings act as a placeholder for Socket.IO init.
SOCKETIO_PATH = 'socket.io'
