# Generated by Django 5.0.14 on 2026-07-31 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('cover_photo', models.FileField(blank=True, null=True, upload_to='covers/')),
                ('signature_image', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=5)),
                ('nationality', models.CharField(blank=True, default='American', max_length=100)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('biography', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='dark', max_length=30)),
                ('dark_mode', models.BooleanField(default=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('time_format', models.CharField(default='12h', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_email', models.EmailField(blank=True, default='', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, default='', max_length=254)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=30)),
                ('alternate_mobile', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_number', models.CharField(blank=True, default='', max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('profile_updated', 'Profile Updated'), ('photo_changed', 'Photo Changed'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('login', 'Login'), ('logout', 'Logout'), ('role_changed', 'Role Changed')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Profile Activity',
                'verbose_name_plural': 'Profile Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('current', 'Current Address'), ('permanent', 'Permanent Address')], default='current', max_length=20)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'address_type')},
            },
        ),
    ]
