# Generated by Django 5.0.14 on 2026-07-31 16:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff'), ('administration', 'Administration'), ('finance', 'Finance'), ('library', 'Library'), ('it_support', 'IT Support'), ('hostel', 'Hostel'), ('transport', 'Transport'), ('security', 'Security')], default='teaching', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='academics.department')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employee_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('visiting', 'Visiting Faculty'), ('adjunct', 'Adjunct Faculty'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full_time', max_length=30)),
                ('joining_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('qualification', models.CharField(blank=True, default='', max_length=200)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('salary_grade', models.CharField(blank=True, default='', max_length=50)),
                ('office_location', models.CharField(blank=True, default='', max_length=150)),
                ('work_email', models.EmailField(blank=True, default='', max_length=254)),
                ('extension_number', models.CharField(blank=True, default='', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='academics.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.designation')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='profiles.userprofile')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Employee Status History',
                'verbose_name_plural': 'Employee Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
