# Generated by Django 5.0.14 on 2026-07-31 17:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('sibling', 'Sibling'), ('other', 'Other')], default='guardian', max_length=30)),
                ('occupation', models.CharField(blank=True, default='', max_length=200)),
                ('employer_name', models.CharField(blank=True, default='', max_length=200)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('education_level', models.CharField(choices=[('none', 'No Formal Education'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], default='bachelor', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('portal_access_enabled', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='profiles.userprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Profile Created'), ('updated', 'Profile Updated'), ('verified', 'Profile Verified'), ('document_uploaded', 'Document Uploaded'), ('document_reviewed', 'Document Reviewed'), ('link_added', 'Student Link Added'), ('link_removed', 'Student Link Removed'), ('portal_login', 'Portal Login'), ('portal_logout', 'Portal Logout'), ('deleted', 'Profile Soft Deleted'), ('restored', 'Profile Restored')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='parents.parent')),
            ],
            options={
                'verbose_name': 'Parent Activity Log',
                'verbose_name_plural': 'Parent Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParentCommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('fee_reminders', models.BooleanField(default=True)),
                ('exam_results', models.BooleanField(default=True)),
                ('general_announcements', models.BooleanField(default=True)),
                ('disciplinary_notices', models.BooleanField(default=True)),
                ('event_invitations', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to='parents.parent')),
            ],
            options={
                'verbose_name': 'Parent Communication Preference',
                'verbose_name_plural': 'Parent Communication Preferences',
            },
        ),
        migrations.CreateModel(
            name='ParentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_proof', 'Government ID Proof'), ('address_proof', 'Address Proof'), ('income_certificate', 'Income Certificate'), ('relationship_certificate', 'Relationship Certificate'), ('court_order', 'Court Order / Legal Guardian'), ('other', 'Other')], default='id_proof', max_length=40)),
                ('document_file', models.FileField(upload_to='parent_documents/')),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parents.parent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parent_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Document',
                'verbose_name_plural': 'Parent Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentParentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True, help_text='Whether this parent is authorised to pick up the student.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='parents.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'verbose_name': 'Student–Parent Link',
                'verbose_name_plural': 'Student–Parent Links',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
