# Generated by Django 5.0.14 on 2026-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_discussionmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
