# Generated by Django 5.0.14 on 2026-06-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_placementdrive_certificaterequest_feerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(default='MASTER OF SCIENCE (INFORMATION TECHNOLOGY) - III /17', max_length=100)),
                ('session', models.CharField(default='2026-2027', max_length=50)),
                ('course_name', models.CharField(default='M.SC .IT- PART- II', max_length=100)),
                ('surname', models.CharField(default='MULANI', max_length=100)),
                ('first_name', models.CharField(default='AMAAN', max_length=100)),
                ('father_name', models.CharField(default='ASIF', max_length=100)),
                ('mother_name', models.CharField(default='SHAHINA', max_length=100)),
                ('marathi_name', models.CharField(default='मुलानी अमान आसिफ', max_length=100)),
                ('gender', models.CharField(default='MALE', max_length=20)),
                ('dob', models.DateField(default='2003-06-20')),
                ('place_of_birth', models.CharField(default='MUMBAI', max_length=100)),
                ('marital_status', models.CharField(default='UNMARRIED', max_length=50)),
                ('religion', models.CharField(default='MUSLIM', max_length=50)),
                ('nationality', models.CharField(default='INDIAN', max_length=50)),
                ('blood_group', models.CharField(default='B+', max_length=10)),
                ('aadhaar_no', models.CharField(default='283896384668', max_length=50)),
                ('mother_tongue', models.CharField(default='HINDI', max_length=50)),
                ('passport_no', models.CharField(default='X4176043', max_length=50)),
                ('voter_id', models.CharField(default='YZI7524861', max_length=50)),
                ('ncc_nss', models.CharField(default='NO', max_length=10)),
                ('employment_status', models.CharField(default='Unemployed', max_length=50)),
                ('birth_state', models.CharField(default='maharastra', max_length=50)),
                ('birth_district', models.CharField(default='andheri', max_length=50)),
                ('birth_tehsil', models.CharField(default='andheri', max_length=50)),
                ('caste_category', models.CharField(default='OBC', max_length=50)),
                ('caste', models.CharField(default='OBC', max_length=50)),
                ('prn_no', models.CharField(default='MSIT250021', max_length=50)),
                ('handicap', models.CharField(default='NO', max_length=10)),
                ('is_orphan', models.CharField(default='NO', max_length=10)),
                ('has_device', models.CharField(default='YES', max_length=10)),
                ('municipal_ward', models.CharField(default='andheri', max_length=50)),
                ('has_internet', models.CharField(default='NO', max_length=10)),
                ('height', models.FloatField(default=171.0)),
                ('weight', models.FloatField(default=58.0)),
                ('abc_id', models.CharField(default='234458422362', max_length=50)),
                ('guardian_occupation', models.CharField(default='OTHER', max_length=100)),
                ('guardian_mobile', models.CharField(default='8652304022', max_length=50)),
                ('guardian_income', models.FloatField(default=150000.0)),
                ('address', models.TextField(default='Omkar sra blg,b1,2011,20th floor,Malad East, Mumbai 97')),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('district', models.CharField(default='MUMBAI', max_length=100)),
                ('tehsil', models.CharField(default='MALAD', max_length=100)),
                ('city', models.CharField(default='MUMBAI', max_length=100)),
                ('pincode', models.CharField(default='400097', max_length=20)),
                ('student_phone', models.CharField(default='9324832187', max_length=50)),
                ('student_email', models.EmailField(default='amaanmulani9@gmail.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
