# Generated by Django 5.0.14 on 2026-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='perm_address',
            field=models.TextField(default='Omkar sra blg,b1,2011,20th floor,Malad East, Mumbai 97'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='perm_city',
            field=models.CharField(default='MUMBAI', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='perm_district',
            field=models.CharField(default='MUMBAI', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='perm_pincode',
            field=models.CharField(default='400097', max_length=20),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='perm_state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='perm_tehsil',
            field=models.CharField(default='MALAD', max_length=100),
        ),
    ]
