# Generated by Django 5.0.14 on 2026-07-31 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('enrollment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('roll_number', models.CharField(blank=True, default='', max_length=50)),
                ('admission_date', models.DateField()),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applicant', 'Applicant'), ('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('alumni', 'Alumni')], db_index=True, default='active', max_length=20)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('International', 'International')], default='General', max_length=30)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('nationality', models.CharField(blank=True, default='American', max_length=100)),
                ('father_name', models.CharField(blank=True, default='', max_length=150)),
                ('father_phone', models.CharField(blank=True, default='', max_length=30)),
                ('mother_name', models.CharField(blank=True, default='', max_length=150)),
                ('mother_phone', models.CharField(blank=True, default='', max_length=30)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=150)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicsession')),
                ('current_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.semester')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='profiles.userprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Status History',
                'verbose_name_plural': 'Student Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
