# Generated by Django 5.0.14 on 2026-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_studentregistration_perm_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='aadhaar_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='abc_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='application_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='birth_district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='birth_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='birth_tehsil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='caste',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='caste_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='guardian_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='guardian_mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='guardian_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='has_device',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='marathi_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='marital_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='mother_tongue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='municipal_ward',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='passport_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='perm_tehsil',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='prn_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='religion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='tehsil',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='voter_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
