# Generated by Django 5.0.14 on 2026-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_attendance_session_alter_attendance_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('event', 'Event/Fest'), ('seminar', 'Seminar'), ('deadline', 'Deadline')], default='event', max_length=20)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationstaff',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
