# Generated by Django 5.0.14 on 2026-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_collegeevent_notificationstaff_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='aadhar_file',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/marksheet/'),
        ),
    ]
