# Generated by Django 5.0.14 on 2026-07-01 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('host_person', models.CharField(max_length=150)),
                ('visit_date', models.DateField()),
                ('pass_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
