# Generated by Django 5.0.14 on 2026-07-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_customuser_user_type_alter_staff_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_card_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
