# Generated by Django 5.0.14 on 2026-07-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_bankdetail_feeparticular_instituteprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksGrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('percent_from', models.IntegerField()),
                ('percent_upto', models.IntegerField()),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='PASS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeLanguageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_placement', models.CharField(default='LTR', max_length=10)),
                ('sidebar_background', models.CharField(default='Light', max_length=20)),
                ('header_background', models.CharField(default='White', max_length=20)),
                ('active_item_background', models.CharField(default='#6c5ce7', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(default='Asia/Karachi', max_length=100)),
                ('currency', models.CharField(default='Dollars (USD)', max_length=100)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('subscription', models.CharField(default='YEARLY', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
