# Generated by Django 5.0.14 on 2026-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_marksgrading_themelanguagesettings_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='staff',
            name='job_letter_password',
            field=models.CharField(blank=True, help_text='Temporary password for job letter display', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_pictures/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
