# Generated by Django 5.0.14 on 2026-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_student_additional_note_student_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_percentage', models.IntegerField(default=40)),
                ('subject_percentage', models.IntegerField(default=33)),
                ('subject_count', models.IntegerField(default=1)),
            ],
        ),
    ]
