# Generated by Django 5.0.14 on 2026-07-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_failcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
