# Generated by Django 5.0.14 on 2026-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_course_class_teacher_course_monthly_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_semesters',
            field=models.IntegerField(default=6, help_text='Total semesters for this course (e.g., 6 for BSCIT, 4 for MSCIT)'),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, help_text='Batch or Division (e.g. Batch A)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='division',
            field=models.CharField(default='', max_length=50),
        ),
    ]
