# Generated by Django 5.0.14 on 2026-07-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_course_total_semesters_student_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('query_date', models.DateField(auto_now_add=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('applicable_for', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=50)),
                ('header_left_text', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField(help_text='Use variables like [name], [course], [dob], etc.')),
                ('footer_left_text', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_center_text', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_right_text', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/backgrounds/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/signatures/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_by', models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Staff', 'Staff')], max_length=50)),
                ('complainer_name', models.CharField(max_length=150)),
                ('complaint_type', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('point', models.IntegerField(default=0)),
                ('is_negative', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='Incoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostalDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_title', models.CharField(max_length=150)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('from_title', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='postal_records/dispatch/')),
            ],
        ),
        migrations.CreateModel(
            name='PostalReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_title', models.CharField(max_length=150)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('to_title', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='postal_records/receive/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBehaviourRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.incident')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='main_app.student')),
            ],
        ),
    ]
