# Generated by Django 5.0.14 on 2026-07-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_customuser_user_type_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Parent'), (5, 'Alumni'), (6, 'CompanyHR'), (7, 'Backoffice')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
