# Generated by Django 5.0.14 on 2026-07-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_customuser_user_type_delete_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff')),
                ('recipient_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.certificatetemplate')),
            ],
        ),
    ]
