# Generated by Django 5.0.14 on 2026-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_staff_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
