# Generated by Django 5.0.14 on 2026-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='receipt_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verification_notes',
            field=models.TextField(blank=True, default='Verified via cryptographic SHA-256 transaction ledger.'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verification_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Suspicious', 'Suspicious'), ('Flagged', 'Flagged')], default='Verified', max_length=20),
        ),
    ]
