# Generated by Django 5.0.14 on 2026-07-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_feepayment_receipt_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('School', 'School'), ('College', 'College')], default='College', max_length=20)),
                ('session_cycle', models.CharField(choices=[('April to March', 'April to March'), ('March to February', 'March to February'), ('January to December', 'January to December'), ('May to April', 'May to April'), ('June to May', 'June to May'), ('July to June', 'July to June'), ('August to July', 'August to July')], default='April to March', max_length=50)),
                ('institution_name', models.CharField(default='CampusPro ERP Institute', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('email', models.EmailField(default='admin@college.edu', max_length=254)),
                ('email_verified', models.BooleanField(default=True)),
                ('website_url', models.URLField(blank=True, default='')),
                ('affiliation_number', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('fee_structure_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('allow_fee_installments', models.BooleanField(default=True)),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_onboarding_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
