# Generated by Django 5.0.14 on 2026-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='digital_signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/certificates/'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='digital_signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_features_vector',
            field=models.TextField(blank=True, help_text='JSON encoded 64-dim facial vector', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/id_cards/'),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='ocr_extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='ocr_mismatch_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='ocr_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='ocr_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Flagged', 'Flagged'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
