# Generated by Django 5.0.14 on 2026-07-31 19:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('phonepe', 'PhonePe'), ('upi', 'UPI'), ('manual', 'Manual / Offline')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Gateway API keys and settings (store secrets via env).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.paymentgateway')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='students.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='fees.studentfee')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gateway_order_id', models.CharField(db_index=True, max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_signature', models.CharField(blank=True, default='', max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded')], db_index=True, default='initiated', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='fees.feereceipt')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentgateway')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.paymentorder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='students.student')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('webhook_received', 'Webhook Received'), ('webhook_duplicate', 'Webhook Duplicate'), ('refund_requested', 'Refund Requested'), ('refund_success', 'Refund Success'), ('refund_failed', 'Refund Failed'), ('signature_verified', 'Signature Verified'), ('signature_failed', 'Signature Verification Failed')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.paymentorder')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-assigned refund ID', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_id', 'gateway'], name='payments_we_event_i_19311a_idx')],
            },
        ),
    ]
