# Generated by Django 5.0.14 on 2026-07-31 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, default='', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], default='prefer_not_to_say', max_length=20)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('International', 'International')], default='General', max_length=30)),
                ('previous_qualification', models.CharField(blank=True, default='', max_length=255)),
                ('percentage_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('application_source', models.CharField(choices=[('online_portal', 'Online Portal'), ('walk_in', 'Walk-In'), ('referral', 'Referral'), ('campus_drive', 'Campus Drive'), ('agent', 'Agent'), ('other', 'Other')], default='online_portal', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('document_verification', 'Document Verification'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=200)),
                ('guardian_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=30)),
                ('guardian_relationship', models.CharField(blank=True, default='guardian', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.department')),
                ('enrolled_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.program')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application_created', 'Application Created'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('student_created', 'Student Created'), ('parent_linked', 'Parent Linked'), ('enrollment_completed', 'Enrollment Completed'), ('seat_allocated', 'Seat Allocated'), ('application_deleted', 'Application Deleted'), ('application_restored', 'Application Restored')], max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='admissions.admissionapplication')),
            ],
            options={
                'verbose_name': 'Admission Audit Log',
                'verbose_name_plural': 'Admission Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('birth_certificate', 'Birth Certificate'), ('marksheet', 'Marksheet'), ('transfer_certificate', 'Transfer Certificate'), ('leaving_certificate', 'Leaving Certificate'), ('photo', 'Passport Photo'), ('signature', 'Signature'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='admission_documents/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admission_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Document',
                'verbose_name_plural': 'Admission Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='admissions.admissionapplication')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('International', 'International')], default='General', max_length=30)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('occupied_seats', models.PositiveIntegerField(default=0)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_matrices', to='academics.academicsession')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_matrices', to='academics.program')),
            ],
            options={
                'verbose_name': 'Seat Matrix',
                'verbose_name_plural': 'Seat Matrices',
                'ordering': ['program', 'category'],
                'unique_together': {('program', 'academic_session', 'category')},
            },
        ),
    ]
