# Generated by Django 5.0.14 on 2026-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='entrance_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_student_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='reserved_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='waitlist_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('document_verification', 'Document Verification'), ('entrance_test', 'Entrance Test'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissiondocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('marksheet', 'Marksheet / Overall'), ('ssc_marksheet', 'SSC Marksheet / 10th'), ('hsc_marksheet', 'HSC Marksheet / 12th'), ('graduation_marksheet', 'Graduation Marksheet'), ('transfer_certificate', 'Transfer Certificate'), ('leaving_certificate', 'Leaving Certificate'), ('photo', 'Passport Photo'), ('photograph', 'Photograph'), ('signature', 'Signature'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('disability_certificate', 'Disability Certificate'), ('other', 'Other Document')], max_length=30),
        ),
    ]
