# Generated by Django 5.0.14 on 2026-07-31 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('government', 'Government'), ('private', 'Private Institution / Trust'), ('merit', 'Merit Based'), ('sports', 'Sports Excellence'), ('minority', 'Minority Welfare'), ('need_based', 'Financial Need Based'), ('fee_waiver', 'Institutional Fee Waiver')], default='merit', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('min_cgpa_requirement', models.FloatField(default=0.0, help_text='Minimum CGPA required for eligibility')),
                ('max_family_income', models.DecimalField(blank=True, decimal_places=2, help_text='Income cap for need-based scholarships', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scholarship Type',
                'verbose_name_plural': 'Scholarship Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat scholarship amount in INR', max_digits=12)),
                ('percentage', models.FloatField(default=0.0, help_text='Percentage discount (0-100%) if percentage-based')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='students.student')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='scholarships.scholarshiptype')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'scholarship_type', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('family_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_cgpa', models.FloatField(default=0.0)),
                ('documents', models.JSONField(blank=True, default=dict, help_text='Uploaded verification document metadata')),
                ('statement_of_purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='academics.academicsession')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scholarship_apps', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to='students.student')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scholarships.scholarshiptype')),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'scholarship_type', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('scholarship_applied', 'Scholarship Applied to Fee'), ('scholarship_renewed', 'Scholarship Renewed'), ('scholarship_revoked', 'Scholarship Revoked')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarships.scholarshipapplication')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_audit_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Scholarship Audit Log',
                'verbose_name_plural': 'Scholarship Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_renewals', to='academics.academicsession')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='scholarships.scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Renewal',
                'verbose_name_plural': 'Scholarship Renewals',
                'ordering': ['-created_at'],
            },
        ),
    ]
